fastapi/full-stack-fastapi-template

{{cookiecutter.project_slug}}/backend/app/app/api/api_v1/endpoints/login.py

:lock: Receive token as body in reset password

Receive token as body in reset password

---

{{cookiecutter.project_slug}}/scripts/build-push.sh

This is the pull request related to issue #97

Use . instead of source in build-push.sh

---

{{cookiecutter.project_slug}}/frontend/src/views/main/Dashboard.vue

In Dashboard the greeting did not show email in case UserProfile exists without fullname.
The condition never came to the else statement

dashboard welcome message to show email if full name doe not exists

---

.github/FUNDING.yml

✨ Add GitHub Sponsors button

---

.github/workflows/issue-manager.yml

⬆️ Update issue-manager

---

.github/workflows/latest-changes.yml

👷 Fix latest-changes GitHub Action token config

👷 Fix latest-changes GitHub Action token config

---

.github/workflows/latest-changes.yml

👷 Fix latest-changes GitHub Action token, strike 2

👷 Fix latest-changes GitHub Action token, strike 2

---

src/backend/app/pyproject.toml
src/backend/backend.dockerfile
src/backend/celeryworker.dockerfile

⬆️ Upgrade Python version and dependencies

⬆️ Upgrade Python version and dependencies

---

src/backend/app/app/api/api_v1/endpoints/items.py

✨ Upgrade items router with new SQLModel models, simplified logic, and new FastAPI Annotated dependencies

✨ Upgrade items router with new SQLModel models, simplified logic, and new FastAPI Annotated dependencies

---

src/backend/app/app/db/init_db.py

Fix positional argument bug in init_db.py

🐛 Fix positional argument bug in `init_db.py`

---

src/backend/app/app/api/api_v1/endpoints/items.py
src/backend/app/app/api/api_v1/endpoints/login.py
src/backend/app/app/api/api_v1/endpoints/users.py

Remove type ignores and add response_model

♻️ Remove type ignores and add `response_model`

---

src/backend/app/app/api/api_v1/endpoints/utils.py

♻️ Refactor API in `utils.py`

---

src/new-frontend/package.json
src/new-frontend/src/client/index.ts
src/new-frontend/src/client/schemas/$Body_login_login_access_token.ts
src/new-frontend/src/client/schemas/$HTTPValidationError.ts
src/new-frontend/src/client/schemas/$ItemCreate.ts
src/new-frontend/src/client/schemas/$ItemOut.ts
src/new-frontend/src/client/schemas/$ItemUpdate.ts
src/new-frontend/src/client/schemas/$Message.ts
src/new-frontend/src/client/schemas/$NewPassword.ts
src/new-frontend/src/client/schemas/$Token.ts
src/new-frontend/src/client/schemas/$UserCreate.ts
src/new-frontend/src/client/schemas/$UserCreateOpen.ts
src/new-frontend/src/client/schemas/$UserOut.ts
src/new-frontend/src/client/schemas/$UserUpdate.ts
src/new-frontend/src/client/schemas/$UserUpdateMe.ts
src/new-frontend/src/client/schemas/$ValidationError.ts

✨ Include schemas in generated frontend client

✨ Include schemas in generated frontend client

---

src/new-frontend/src/App.tsx
src/new-frontend/src/pages/Layout.tsx

✨ Add Layout to App

---

src/new-frontend/src/components/Sidebar.tsx
src/new-frontend/src/components/SidebarItems.tsx

🐛  Add `onClose` to `SidebarItems`

---

src/new-frontend/package.json
src/new-frontend/src/store/items-store.tsx
src/new-frontend/src/store/user-store.tsx
src/new-frontend/src/store/users-store.tsx

✨ Add state store to new frontend

---

src/new-frontend/src/App.tsx
src/new-frontend/src/pages/NotFound.tsx

✨ Add `Not Found` page

---

.pre-commit-config.yaml
src/backend/.flake8
src/backend/mypy.ini
src/backend/pyproject.toml

➕ Replace black, isort, flake8, autoflake with ruff and upgrade mypy

➕ Replace black, isort, flake8, autoflake with ruff and upgrade mypy

---

src/.env

🔧 Update .env to allow local debug for the backend

🔧 Update .env to allow local debug for the backend

---

.vscode/launch.json

🔧 Add VS Code debug configs

---

new-frontend/.prettierrc
new-frontend/package-lock.json
new-frontend/package.json

⚙️ Add Prettier config

---

new-frontend/.prettierignore
new-frontend/package.json

🙈 Add .prettierignore and include client folder

🙈 Add .prettierignore and include client folder

---

frontend/src/components/UserSettings/ChangePassword.tsx

🔥 Remove unnecessary validation

🔥 Remove unnecessary validation

---

deployment.md

📝 Update deployment docs to use a different directory for traefik-public

📝 Update deployment docs to use a different directory for traefik-public

---

backend/app/worker.py

🐛 Set up Sentry only when used

🐛 Set up Sentry only when used

---

frontend/src/routes/__root.tsx

🔧 Set TanStack Router devtools only in dev mode

🔧 Set TanStack Router devtools only in dev mode

---

frontend/src/components/Admin/AddUser.tsx
frontend/src/components/Admin/EditUser.tsx
frontend/src/components/Common/DeleteAlert.tsx
frontend/src/components/Common/Navbar.tsx
frontend/src/components/Common/Sidebar.tsx
frontend/src/components/Common/SidebarItems.tsx
frontend/src/components/Items/AddItem.tsx
frontend/src/components/Items/EditItem.tsx
frontend/src/components/UserSettings/ChangePassword.tsx
frontend/src/components/UserSettings/DeleteConfirmation.tsx
frontend/src/components/UserSettings/UserInformation.tsx
frontend/src/routes/_layout/admin.tsx
frontend/src/routes/_layout/items.tsx
frontend/src/routes/login.tsx
frontend/src/theme.tsx

🎨 Update theme

---

.github/workflows/test.yml

👷 Tweak test GitHub Action names

👷 Tweak test GitHub Action names

---

.vscode/launch.json

🔧 Update VS Code debug config

---

deployment.md

📝 Add docs for wildcard domains

📝 Add docs for wildcard domains

---

.env
README.md
copier.yml
deployment.md

🔧 Add a default Flower password

🔧 Add a default Flower password

---

frontend/src/components/UserSettings/UserInformation.tsx
frontend/src/routes/_layout/index.tsx

🎨 Adjust color and spacing

---

backend/app/tests/api/routes/test_users.py

✅ Add test for deleting user without privileges

✅ Add test for deleting user without privileges

---

backend/app/api/routes/users.py

🐛 Fix allowing a user to update the email to the same email they already have

---

backend/app/core/config.py

🔒️ Ensure the default values of "changethis" are not deployed

🔒️ Ensure the default values of "changethis" are not deployed

---

.env
README.md
backend/app/core/db.py
frontend/index.html
release-notes.md

🚚 Rename project to Full Stack FastAPI Template

🚚 Rename project to Full Stack FastAPI Template

---

img/github-social-preview.svg

🍱 Update GitHub image

---

backend/poetry.lock

📌 Upgrade Poetry lock dependencies

📌 Upgrade Poetry lock dependencies

---

README.md

📝 Update `README.md`, dark mode screenshot position

---

docker-compose.yml

♻ Update Docker image to prevent errors in M1 Macs

---

.pre-commit-config.yaml

⚙️ Update pre-commit config with Prettier and ESLint

⚙️ Update pre-commit config with Prettier and ESLint

---

README.md

📝 Update `README.md`

---

frontend/nginx.conf

🐛 Fix 403 when the frontend has a directory without an index.html

🐛 Fix 403 when the frontend has a directory without an index.html

---

frontend/biome.json

🎨 Update quote style in biome formatter

🎨 Update quote style in biome formatter

---

development.md

Fixed Swagger and ReDoc urls to use http instead of https.

📝 Fix localhost URLs in `development.md`

---

.pre-commit-config.yaml

🔧 Add Biome to pre-commit config

🔧 Add Biome to pre-commit config

---

.github/workflows/latest-changes.yml
.github/workflows/smokeshow.yml

👷 Update CI GitHub Actions to allow running in private repos

👷 Update CI GitHub Actions to allow running in private repos

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml
README.md
deployment.md

✨ Add support for deploying multiple environments (staging, production) to the same server

✨ Add support for deploying multiple environments (staging, production) to the same server

---

docker-compose.override.yml
docker-compose.yml

🔥 Remove deprecated Docker Compose version key

🔥 Remove deprecated Docker Compose version key

---

frontend/package-lock.json
frontend/package.json
frontend/src/routes/_layout.tsx
frontend/src/routes/_layout/admin.tsx
frontend/src/routes/_layout/index.tsx
frontend/src/routes/_layout/items.tsx
frontend/src/routes/_layout/settings.tsx
frontend/src/routes/login.tsx
frontend/src/routes/recover-password.tsx
frontend/src/routes/reset-password.tsx

🔥 Remove unused exports and update dependencies

🔥 Remove unused exports and update dependencies

---

frontend/src/components/Admin/AddUser.tsx
frontend/src/components/Admin/EditUser.tsx
frontend/src/components/Common/DeleteAlert.tsx
frontend/src/components/Common/Sidebar.tsx
frontend/src/components/Common/SidebarItems.tsx
frontend/src/components/Items/AddItem.tsx
frontend/src/components/Items/EditItem.tsx
frontend/src/components/UserSettings/ChangePassword.tsx
frontend/src/components/UserSettings/DeleteConfirmation.tsx
frontend/src/components/UserSettings/UserInformation.tsx
frontend/src/hooks/useAuth.ts
frontend/src/main.tsx
frontend/src/routes/_layout/admin.tsx
frontend/src/routes/_layout/index.tsx
frontend/src/routes/_layout/items.tsx
frontend/src/routes/_layout/settings.tsx
frontend/src/routes/reset-password.tsx

🎨 Format frontend

---

frontend/src/utils.ts

🐛 Fix bug when resetting password
Related to https://github.com/tiangolo/full-stack-fastapi-template/discussions/1170

🐛 Fix bug when resetting password

---

backend/app/tests/api/routes/test_users.py

🔥 Remove duplicated code

---

backend/README.md

📝 Add `Enabling Open User Registration` to backend docs
Related to https://github.com/tiangolo/full-stack-fastapi-template/discussions/1190

📝 Add `Enabling Open User Registration` to backend docs

---

deployment.md

The URL prefixes have to be Changed

✏️ Fix Adminer URL in `deployment.md`

---

.github/workflows/smokeshow.yml

👷 Update Smokeshow download artifact GitHub Action

👷 Update Smokeshow download artifact GitHub Action

---

docker-compose.yml

♻️ Refactor redirect labels to simplify removing the frontend

♻️ Refactor redirect labels to simplify removing the frontend

---

frontend/src/components/UserSettings/Appearance.tsx
frontend/src/components/UserSettings/ChangePassword.tsx
frontend/src/components/UserSettings/UserInformation.tsx
frontend/src/utils.ts

⚒️ Add minor frontend tweaks

---

release-notes.md

📝 Update release-notes.md

---

frontend/src/client/services.ts

♻️ Update client services

---

frontend/src/components/UserSettings/DeleteConfirmation.tsx

♻️ Update DeleteConfirmation component to use new service

♻️ Update DeleteConfirmation component to use new service

---

docker-compose.override.yml
docker-compose.traefik.yml
docker-compose.yml

⬆️ Upgrade Traefik

---

frontend/src/components/UserSettings/DeleteConfirmation.tsx
frontend/src/routes/__root.tsx

🎨 Format and lint 

---

frontend/src/routes/login.tsx

Prevent error if username or password are empty.

♻️ Update `login.tsx` to prevent error if username or password are empty

---

frontend/src/components/UserSettings/ChangePassword.tsx
frontend/src/components/UserSettings/UserInformation.tsx

♻️ Update form inputs width

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml

🔧 Update deploy-staging and deploy-production workflows to exclude the main repository

🔧 Update deploy workflows to exclude the main repository

---

.github/ISSUE_TEMPLATE/config.yml
.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml
README.md
backend/app/core/db.py

📝 Update links from tiangolo repo to fastapi org repo

📝 Update links from tiangolo repo to fastapi org repo

---

.github/workflows/labeler.yml

👷 Update GitHub Action labeler permissions

👷 Update GitHub Action labeler permissions

---

.github/workflows/labeler.yml

👷 Update GitHub Action labeler dependencies

👷 Update GitHub Action labeler dependencies

---

.github/labeler.yml
.github/workflows/labeler.yml

👷 Update GitHub Action labeler to add only one label

👷 Update GitHub Action labeler to add only one label

---

.github/labeler.yml

👷 Update configs for labeler

---

.github/labeler.yml

👷 Update `.github/labeler.yml`

---

.github/labeler.yml

🐛 Fix in `.github/labeler.yml`

🐛 Fix in `.github/labeler.yml`

---

docker-compose.yml

🔥 Simplify Traefik, remove www-redirects that add complexity

🔥 Simplify Traefik, remove www-redirects that add complexity

---

backend/README.md
development.md
docker-compose.override.yml

♻️ Use Docker Compose watch
Ref: https://docs.docker.com/compose/how-tos/file-watch/
Got the idea from uv's docs: https://docs.astral.sh/uv/guides/integration/docker/#configuring-watch-with-docker-compose

♻️ Use Docker Compose `watch`

---

backend/Dockerfile
docker-compose.override.yml
docker-compose.yml

🔥 Remove logic for development dependencies and Jupyter, it was never documented, and I no longer use that trick

🔥 Remove logic for development dependencies and Jupyter, it was never documented, and I no longer use that trick

---

backend/Dockerfile

💡 Add comments to Dockerfile with uv references

💡 Add comments to Dockerfile with uv references

---

.github/workflows/lint-backend.yml

👷 Add GitHub Actions workflow to lint backend apart from tests

👷 Add GitHub Actions workflow to lint backend apart from tests

---

backend/app/core/config.py

♻️ Update settings to use top level `.env` file

♻️ Update settings to use top level `.env` file

---

scripts/generate-client.sh

🔨 Update `generate-client.sh` script, make it fail on errors, fix generation

🔨 Update `generate-client.sh` script, make it fail on errors, fix generation

---

.github/workflows/generate-client.yml
.github/workflows/lint-backend.yml
.github/workflows/test-backend.yml

👷 Use uv cache on GitHub Actions

👷 Use uv cache on GitHub Actions

---

.github/workflows/generate-client.yml

👷 Generate and commit client only on same repo PRs, on forks, show the error

👷 Generate and commit client only on same repo PRs, on forks, show the error

---

backend/Dockerfile

🔧 Add `ENV PYTHONUNBUFFERED=1` to log output directly to Docker

🔧 Add `ENV PYTHONUNBUFFERED=1` to log output directly to Docker

---

.github/workflows/issue-manager.yml

👷 Update issue manager workflow

👷 Update issue manager workflow

---

frontend/README.md

To remove the frontend, we need to remove playwright service as well.

📝 Update `frontend/README.md` to also remove Playwright when removing Frontend

---

backend/Dockerfile

⬆️ Update Dockerfile to use uv version 0.5.11

⬆️ Update Dockerfile to use uv version 0.5.11

---

frontend/src/routes/signup.tsx

Hi, this is my first PR here. Let me know if I can do anything better, I did not find contribution guide.
This PR fixes link between email label and input field in signup page.

🧑‍🔧 Replace correct value for 'htmlFor'

---

backend/app/api/routes/users.py

Remove manual item deletion - cascade delete handles this

♻️ Remove redundant item deletion code leveraging cascade delete

---

frontend/README.md

Fix incorrect script name which was generate-frontend-client.sh and now is generate-client.sh

📝 Update Frontend README.md

---

frontend/src/main.tsx

🔧 Remove unused context from router creation

🔧 Remove unused context from router creation

---

.github/dependabot.yml
frontend/openapi-ts.config.ts
frontend/package-lock.json
frontend/package.json
frontend/src/client/schemas.gen.ts

⬆️ Update @hey-api/openapi-ts dependency version and update dependabot config
Pin the exact version and update the Dependabot config to prevent upgrading this dependency unexpectedly. According to their docs, this package does not follow semantic versioning and may introduce breaking changes in minor releases. We'll continue using the legacy client for now.

⬆️ Update @hey-api/openapi-ts dependency version and update dependabot config

---

backend/pyproject.toml
backend/scripts/test.sh

🔧 Update coverage configuration and simplify test script

🔧 Update coverage configuration and simplify test script
