fastapi/full-stack-fastapi-template

{{cookiecutter.project_slug}}/backend/app/app/api/api_v1/endpoints/user.py
Changed doctring from "Get a specific user by username (email)" to "Get a specific user by id". Not the biggest PR in the world ;)
=> Fixed read_user_by_id docstring

{{cookiecutter.project_slug}}/frontend/Dockerfile, {{cookiecutter.project_slug}}/frontend/nginx-backend-not-found.conf
:bug: Fix frontend hijacking /docs in development. Using latest https://github.com/tiangolo/node-frontend with custom Nginx configs in frontend.
=> Fix frontend hijacking /docs in development

{{cookiecutter.project_slug}}/backend/app/Pipfile, {{cookiecutter.project_slug}}/backend/backend.dockerfile, {{cookiecutter.project_slug}}/backend/celeryworker.dockerfile, {{cookiecutter.project_slug}}/backend/tests.dockerfile
changed dockerfiles and Pipfile
details of usecase and issues on the way in https://github.com/tiangolo/full-stack-fastapi-postgresql/issues/8
=> Pushes up versions to python to 3.7 and celery to ~=4.3

{{cookiecutter.project_slug}}/docker-compose.shared.admin.yml, {{cookiecutter.project_slug}}/docker-compose.shared.base-images.yml, {{cookiecutter.project_slug}}/env-flower.env
Tested that the flower UI works under both configurations described in the edits.
Feel free to tweak as you like.
=> Modified docker configuration for flower

{{cookiecutter.project_slug}}/backend/app/app/api/api_v1/endpoints/items.py
Swapped `read_user_me` for `read_item` for the single item get request. Looks like it was copied from the user paths and not updated. Doesn't change functionality but is more readable as it didn't make sense to have it called `read_user_me` and might be confusing. While I was at it I also updated the status code for not found to 404, so it's a more helpful error message if not found.
=> Fix typo in `read_item` GET view

{{cookiecutter.project_slug}}/backend/app/app/schemas/user.py, {{cookiecutter.project_slug}}/backend/app/app/tests/api/api_v1/test_users.py, {{cookiecutter.project_slug}}/backend/app/app/tests/crud/test_user.py, {{cookiecutter.project_slug}}/backend/app/app/tests/utils/user.py, {{cookiecutter.project_slug}}/backend/app/app/tests/utils/utils.py, {{cookiecutter.project_slug}}/backend/backend.dockerfile, {{cookiecutter.project_slug}}/backend/celeryworker.dockerfile, {{cookiecutter.project_slug}}/backend/tests.dockerfile
Add email validation in User model with pydantic EmailStr.
Btw have you considered using pipenv or requirements.txt files for python packages dependencies?
Installing packages one by one in dockerfiles is kind of ugly.
=> Add email validation

{{cookiecutter.project_slug}}/docker-compose.deploy.labels.yml
:recycle: Simplify Traefik labels in services, taking the ideas from https://github.com/tiangolo/dockerswarm.rocks/pull/22
=> Simplify Traefik labels in services

{{cookiecutter.project_slug}}/backend/app/app/db/base_class.py
Minor fix to simplify the code in DB base class declaration, by making use of the @as_declarative decorator introduced in SQLAlchemy 0.8.3.
=> Simplify DB base class declaration

hooks/post_gen_project.py
:bug: Fix Windows line endings for shell scripts after generation.
This uses Cookiecutter hooks and pathlib to replace all CR LF characters with LF in `*.sh` files.
https://cookiecutter.readthedocs.io/en/latest/advanced/hooks.html
=> Fix Windows line endings for shell scripts after generation

README.md, cookiecutter.json, {{cookiecutter.project_slug}}/.env, {{cookiecutter.project_slug}}/README.md, {{cookiecutter.project_slug}}/cookiecutter-config-file.yml, {{cookiecutter.project_slug}}/docker-compose.deploy.networks.yml
:pushpin: Make the public Traefik network a fixed default to simplify development of the project itself.
It's still configurable after generating a project, but this will allow using the same Docker Compose files during development without re-generating a project every time.
=> Make the public Traefik network a fixed default

.gitignore, .travis.yml, CONTRIBUTING.md, README.md, dev-fsfp-config.yml, scripts/dev-fsfp-back.sh, scripts/dev-fsfp.sh, scripts/dev-link.sh, scripts/discard-dev-files.sh, scripts/test.sh, testing-config.yml, {{cookiecutter.project_slug}}/README.md
:recycle: Simplify scripts.
Refactor script locations to clean up the project.
Update generated README with all the new changes.
Add `CONTRIBUTING.md` guide.
=> Simplify scripts

README.md, {{cookiecutter.project_slug}}/README.md
:memo: Add docs about removing the frontend
=> Add docs about removing the frontend

README.md, {{cookiecutter.project_slug}}/backend/app/app/crud/__init__.py, {{cookiecutter.project_slug}}/backend/app/app/schemas/item.py, {{cookiecutter.project_slug}}/backend/app/app/tests/api/api_v1/test_items.py, {{cookiecutter.project_slug}}/backend/app/scripts/lint.sh
=> Format fixes

{{cookiecutter.project_slug}}/backend/app/app/tests/api/api_v1/test_celery.py, {{cookiecutter.project_slug}}/backend/app/app/tests/api/api_v1/test_items.py, {{cookiecutter.project_slug}}/backend/app/app/tests/api/api_v1/test_login.py, {{cookiecutter.project_slug}}/backend/app/app/tests/api/api_v1/test_users.py, {{cookiecutter.project_slug}}/backend/app/app/tests/conftest.py, {{cookiecutter.project_slug}}/backend/app/app/tests/utils/user.py, {{cookiecutter.project_slug}}/backend/app/app/tests/utils/utils.py, {{cookiecutter.project_slug}}/backend/app/app/tests_pre_start.py
:sparkles: Test using the `TestClient`
=> Test using the TestClient

{{cookiecutter.project_slug}}/README.md
:memo: Add docs about reporting coverage in HTML
=> Add docs about reporting coverage in HTML

{{cookiecutter.project_slug}}/.env, {{cookiecutter.project_slug}}/docker-compose.override.yml, {{cookiecutter.project_slug}}/docker-compose.yml
✨ Upgrade Traefik to version 2.
Now that DockerSwarm.rocks defaults to Traefik v2. :tada:
=> ✨ Traefik v2

{{cookiecutter.project_slug}}/README.md, {{cookiecutter.project_slug}}/docker-compose.override.yml, {{cookiecutter.project_slug}}/docker-compose.yml, {{cookiecutter.project_slug}}/scripts/build-push.sh, {{cookiecutter.project_slug}}/scripts/build.sh, {{cookiecutter.project_slug}}/scripts/deploy.sh
🔊 Add consistent errors for env vars not set
=> 🔊 Add consistent errors for env vars not set

README.md
📝 Update README with in construction notice
=> 📝 Update README with in construction notice

src/.env
🔧 Add missing dotenv variables
=> 🔧 Add missing dotenv variables

src/.env, src/frontend/Dockerfile, src/frontend/nginx.conf
♻️ Refactor frontend Docker build setup, use plain NodeJS, use custom Nginx config, fix build for old Vue
=> ♻️ Refactor frontend Docker build setup, use plain NodeJS, use custom Nginx config, fix build for old Vue

src/backend/app/app/main.py, src/new-frontend/README.md, src/new-frontend/modify-openapi-operationids.js, src/new-frontend/package-lock.json, src/new-frontend/package.json, src/new-frontend/src/client/core/ApiError.ts, src/new-frontend/src/client/core/ApiRequestOptions.ts, src/new-frontend/src/client/core/ApiResult.ts, src/new-frontend/src/client/core/CancelablePromise.ts, src/new-frontend/src/client/core/OpenAPI.ts, src/new-frontend/src/client/core/request.ts, src/new-frontend/src/client/index.ts, src/new-frontend/src/client/models/Body_login_login_access_token.ts, src/new-frontend/src/client/models/Body_login_reset_password.ts, src/new-frontend/src/client/models/HTTPValidationError.ts, src/new-frontend/src/client/models/ItemCreate.ts, src/new-frontend/src/client/models/ItemOut.ts, src/new-frontend/src/client/models/ItemUpdate.ts, src/new-frontend/src/client/models/Msg.ts, src/new-frontend/src/client/models/Token.ts, src/new-frontend/src/client/models/User.ts, src/new-frontend/src/client/models/UserCreate.ts, src/new-frontend/src/client/models/UserCreateOpen.ts, src/new-frontend/src/client/models/UserOut.ts, src/new-frontend/src/client/models/ValidationError.ts, src/new-frontend/src/client/services/ItemsService.ts, src/new-frontend/src/client/services/LoginService.ts, src/new-frontend/src/client/services/UsersService.ts, src/new-frontend/src/client/services/UtilsService.ts
=> ✨ Add client in frontend and client generation

src/backend/app/app/api/api_v1/endpoints/login.py, src/backend/app/app/api/deps.py, src/backend/app/app/crud/__init__.py, src/backend/app/app/models.py
=> ✨ Update code for login API

src/backend/app/app/api/api_v1/endpoints/items.py, src/backend/app/app/api/api_v1/endpoints/users.py, src/backend/app/app/models.py
Re-enable user update path operations for frontend client generation
=> ♻️ Re-enable user update path operations for frontend client generation

src/new-frontend/src/client/index.ts, src/new-frontend/src/client/models/Message.ts, src/new-frontend/src/client/models/NewPassword.ts, src/new-frontend/src/client/models/Token.ts, src/new-frontend/src/client/models/UserUpdate.ts, src/new-frontend/src/client/models/UserUpdateMe.ts, src/new-frontend/src/client/services/LoginService.ts, src/new-frontend/src/client/services/UsersService.ts, src/new-frontend/src/client/services/UtilsService.ts
✨ Regenerate frontend client with recent changes
=> ✨ Regenerate frontend client with recent changes

src/new-frontend/src/components/Sidebar.tsx, src/new-frontend/src/components/SidebarItems.tsx, src/new-frontend/src/components/UserInfo.tsx, src/new-frontend/src/pages/Layout.tsx
=> ✨ Add Sidebar to new frontend

src/new-frontend/src/App.tsx, src/new-frontend/src/components/ActionsMenu.tsx, src/new-frontend/src/components/Navbar.tsx, src/new-frontend/src/components/Sidebar.tsx, src/new-frontend/src/components/SidebarItems.tsx, src/new-frontend/src/components/UserInfo.tsx, src/new-frontend/src/pages/auth/Login.tsx, src/new-frontend/src/pages/main/Admin.tsx, src/new-frontend/src/pages/main/Dashboard.tsx, src/new-frontend/src/pages/main/Items.tsx, src/new-frontend/src/pages/main/Profile.tsx, src/new-frontend/src/pages/modals/CreateItem.tsx, src/new-frontend/src/pages/modals/CreateUser.tsx, src/new-frontend/src/pages/modals/DeleteAlert.tsx, src/new-frontend/src/pages/modals/EditItem.tsx, src/new-frontend/src/pages/modals/EditUser.tsx, src/new-frontend/src/pages/panels/Appearance.tsx, src/new-frontend/src/pages/panels/ChangePassword.tsx, src/new-frontend/src/pages/panels/DeleteAccount.tsx, src/new-frontend/src/pages/panels/UserInformation.tsx
✨ Add new pages, components, panels, modals, and theme; refactor existing components
=> ✨ Add new pages, components, panels, modals, and theme; refactor and improvements in existing components

src/backend/app/app/api/api_v1/endpoints/items.py, src/backend/app/app/api/api_v1/endpoints/users.py, src/new-frontend/src/client/services/ItemsService.ts, src/new-frontend/src/client/services/UsersService.ts, src/new-frontend/src/store/users-store.tsx
✨ Add delete_user; refactor delete_item
=> ✨ Add delete_user; refactor delete_item

src/new-frontend/src/components/ActionsMenu.tsx, src/new-frontend/src/components/Sidebar.tsx, src/new-frontend/src/components/SidebarItems.tsx, src/new-frontend/src/components/UserMenu.tsx, src/new-frontend/src/modals/DeleteConfirmation.tsx, src/new-frontend/src/pages/Admin.tsx, src/new-frontend/src/pages/Dashboard.tsx, src/new-frontend/src/pages/Items.tsx, src/new-frontend/src/pages/Layout.tsx, src/new-frontend/src/pages/RecoverPassword.tsx, src/new-frontend/src/pages/UserSettings.tsx, src/new-frontend/src/panels/Appearance.tsx, src/new-frontend/src/panels/ChangePassword.tsx, src/new-frontend/src/panels/DeleteAccount.tsx, src/new-frontend/src/panels/UserInformation.tsx
✨ Add dark mode to new-frontend
=> ✨ Add dark mode to new-frontend and conditional sidebar items

src/backend/app/app/api/api_v1/endpoints/items.py, src/backend/app/app/models.py, src/backend/app/pyproject.toml
✨ Add support for updating items and upgrade SQLModel to 0.0.16 (which supports model object updates)
For more details, check the SQLModel docs: https://sqlmodel.tiangolo.com/tutorial/fastapi/update/ and https://sqlmodel.tiangolo.com/tutorial/fastapi/update-extra-data/
=> ✨ Add support for updating items and upgrade SQLModel to 0.0.16 (which supports model object updates)

src/docker-compose.override.yml, src/docker-compose.yml
♻ Re-structure Docker Compose files, discard Docker Swarm specific logic
=> ♻ Re-structure Docker Compose files, discard Docker Swarm specific logic

src/backend/app/api/api_v1/endpoints/users.py, src/new-frontend/src/components/Common/Sidebar.tsx, src/new-frontend/src/components/Common/UserMenu.tsx, src/new-frontend/src/components/UserSettings/DeleteConfirmation.tsx, src/new-frontend/src/hooks/useAuth.tsx, src/new-frontend/src/store/items-store.tsx, src/new-frontend/src/store/users-store.tsx
✨ Support delete own account and other tweaks
=> ✨ Support delete own account and other tweaks

src/new-frontend/src/components/Admin/AddUser.tsx, src/new-frontend/src/components/Admin/EditUser.tsx, src/new-frontend/src/components/Common/DeleteAlert.tsx, src/new-frontend/src/components/Items/AddItem.tsx, src/new-frontend/src/components/Items/EditItem.tsx, src/new-frontend/src/components/UserSettings/Appearance.tsx, src/new-frontend/src/components/UserSettings/DeleteConfirmation.tsx, src/new-frontend/src/components/UserSettings/UserInformation.tsx, src/new-frontend/src/pages/Login.tsx
✨ Add form validation to Admin, Items and Login
=> ✨ Add form validation to Admin, Items and Login

src/.env, src/backend/app/core/config.py, src/backend/app/main.py, src/docker-compose.yml
♻️ Refactor and update CORS, remove trailing slash from new Pydantic v2
=> ♻️ Refactor and update CORS, remove trailing slash from new Pydantic v2

src/backend/app/utils.py, src/new-frontend/src/pages/RecoverPassword.tsx, src/new-frontend/src/pages/ResetPassword.tsx, src/new-frontend/src/routes/public_route.tsx
✨ Add password reset functionality
=> ✨ Add password reset functionality

new-frontend/package.json
=> 🔧 Add script for ESLint

frontend/src/components/UserSettings/DeleteAccount.tsx, frontend/src/components/UserSettings/DeleteConfirmation.tsx
💬 Improve Delete Account description and confirmation
=> 💬 Improve Delete Account description and confirmation

backend/README.md, backend/app/api/deps.py, backend/app/api/routes/login.py, backend/app/api/routes/users.py, backend/app/api/routes/utils.py, backend/app/tests/api/api_v1/test_login.py, backend/app/tests/api/api_v1/test_users.py, backend/app/utils.py
♻️ Refactor email logic to allow re-using util functions for testing and development
=> ♻️ Refactor email logic to allow re-using util functions for testing and development

.gitattributes
Added .gitattributes to ensure LF endings in scripts files despite operative system and repository configuration
=> 🔧 Add `.gitattributes` file to ensure LF endings for `.sh` files

backend/README.md, backend/app/core/config.py, backend/app/utils.py
♻️ Refactor logic to allow running pytest tests locally
=> ♻️ Refactor logic to allow running pytest tests locally

.github/workflows/test.yml, backend/backend.dockerfile, backend/tests-start.sh
👷 Add Lint to GitHub Actions outside of tests
=> 👷 Add Lint to GitHub Actions outside of tests

README.md
=> 📝 Update `README.md`

README.md
=> ✏ Update header titles for consistency

frontend/src/components/Admin/AddUser.tsx, frontend/src/components/Admin/EditUser.tsx, frontend/src/components/Common/ActionsMenu.tsx, frontend/src/components/Items/AddItem.tsx, frontend/src/components/Items/EditItem.tsx, frontend/src/components/UserSettings/ChangePassword.tsx, frontend/src/components/UserSettings/DeleteConfirmation.tsx, frontend/src/components/UserSettings/UserInformation.tsx, frontend/src/routes/reset-password.tsx
=> 🛠️ Minor changes in frontend

frontend/src/components/UserSettings/DeleteAccount.tsx, frontend/src/routes/login.tsx, frontend/src/routes/recover-password.tsx, frontend/src/routes/reset-password.tsx
🎨 Replace buttons styling for variants for consistency
=> 🎨 Replace buttons styling for variants for consistency

.pre-commit-config.yaml
🔥 Remove ESLint and Prettier from pre-commit config
=> 🔥 Remove ESLint and Prettier from pre-commit config

.github/workflows/latest-changes.yml, deployment.md
📝 Add docs about CI keys, LATEST_CHANGES and SMOKESHOW_AUTH_KEY
=> 📝 Add docs about CI keys, LATEST_CHANGES and SMOKESHOW_AUTH_KEY

README.md
📝 Update instructions to clone for a private repo, including updates
=> 📝 Update instructions to clone for a private repo, including updates

.pre-commit-config.yaml, frontend/src/components/Admin/AddUser.tsx, frontend/src/components/Admin/EditUser.tsx, frontend/src/components/UserSettings/UserInformation.tsx, frontend/src/routes/login.tsx, frontend/src/routes/recover-password.tsx, frontend/src/utils.ts
:recycle: Add email pattern and refactor
=> ♻️ Add email pattern and refactor in frontend

frontend/src/components/Admin/AddUser.tsx, frontend/src/components/Admin/EditUser.tsx, frontend/src/components/Common/ActionsMenu.tsx, frontend/src/components/Common/DeleteAlert.tsx, frontend/src/components/Common/Navbar.tsx, frontend/src/components/Common/NotFound.tsx, frontend/src/components/Common/Sidebar.tsx, frontend/src/components/Common/SidebarItems.tsx, frontend/src/components/Common/UserMenu.tsx, frontend/src/components/Items/AddItem.tsx, frontend/src/components/Items/EditItem.tsx, frontend/src/components/UserSettings/Appearance.tsx, frontend/src/components/UserSettings/ChangePassword.tsx, frontend/src/components/UserSettings/DeleteAccount.tsx, frontend/src/components/UserSettings/DeleteConfirmation.tsx, frontend/src/components/UserSettings/UserInformation.tsx, frontend/src/hooks/useAuth.ts
:recycle: Refactor and remove React.FC
=> ♻️ Refactor and remove `React.FC`

frontend/src/components/Admin/AddUser.tsx, frontend/src/components/Admin/EditUser.tsx, frontend/src/components/Items/AddItem.tsx, frontend/src/components/Items/EditItem.tsx, frontend/src/components/UserSettings/ChangePassword.tsx, frontend/src/components/UserSettings/DeleteConfirmation.tsx, frontend/src/components/UserSettings/UserInformation.tsx, frontend/src/hooks/useAuth.ts
=> 🎨 Format imports

backend/app/tests/api/routes/test_login.py, backend/app/tests/api/routes/test_users.py, backend/app/tests/scripts/test_backend_pre_start.py, backend/app/tests/scripts/test_test_pre_start.py, backend/pyproject.toml, backend/scripts/format-imports.sh, backend/scripts/format.sh, backend/scripts/lint.sh
This PR removes the isort configuration from pyproject.toml
The configuration options we had set aren't supported by ruff just yet,
but I think the default config is pretty much what we want (after all
running ruff now didn't change anything).
I'm also removing the calls to isort, since we want to use ruff for this.
I've also update the `format.sh` script to use ruff, do we want to keep it?
=> 🔥 Remove isort configuration, since we use Ruff now

backend/app/api/routes/users.py, backend/app/tests/api/routes/test_items.py, backend/app/tests/api/routes/test_users.py, backend/pyproject.toml
I noticed in some places we have unused arguments (especially `db` in tests). I've
added the `ARG001` rule to prevent that 😊
=> 🚨 Enable `ARG001` to prevent unused arguments

frontend/src/client/models.ts, frontend/src/client/schemas.ts, frontend/src/client/services.ts, frontend/src/components/Admin/EditUser.tsx, frontend/src/components/Common/ActionsMenu.tsx, frontend/src/components/Common/Sidebar.tsx, frontend/src/components/Common/SidebarItems.tsx, frontend/src/components/Items/EditItem.tsx, frontend/src/components/UserSettings/DeleteConfirmation.tsx, frontend/src/components/UserSettings/UserInformation.tsx, frontend/src/hooks/useAuth.ts, frontend/src/routes/_layout/admin.tsx, frontend/src/routes/_layout/index.tsx, frontend/src/routes/_layout/settings.tsx
=> ♻️ Regenerate frontend client

frontend/src/hooks/useAuth.ts
Tiny PR to check for (mostly) network errors, it shows like this:
This happens when the user is not connected to the network or when the backend is down
=> 🥅 Handle AxiosErrors in Login page

release-notes.md
=> 📝 Update release-notes.md

frontend/package-lock.json, frontend/package.json, frontend/src/routes/_layout/items.tsx
I've also added a very simple skeleton
https://github.com/tiangolo/full-stack-fastapi-template/assets/667029/391d693d-9a00-467d-9cb6-e53d249b4b96
=> ✨ Use suspense for items page

backend/app/tests/api/routes/test_login.py
The `test_reset_password` test changes user password. It will break other tests becuase `get_superuser_token_headers` function won't able to get access_token.
It relates to #217
=> ♻️ Fix tests when first superuser password is changed in .env

backend/app/api/deps.py, backend/app/api/routes/users.py, backend/app/tests/api/routes/test_users.py
♻️ Add delete_user_me  endpoint and corresponding test cases
=> ♻️ Add delete_user_me endpoint and corresponding test cases

docker-compose.override.yml
The network config of the proxy service for the local docker setup (docker-compose.override.yaml) is missing and therefore the proxy service can't reach the backend service (produces Gateway Timeouts).
See https://github.com/tiangolo/full-stack-fastapi-template/discussions/1183
=> 🐛 Fix local Traefik proxy network config to fix Gateway Timeouts

frontend/src/routes/_layout/index.tsx
Use up-to-date logged-in user value from `useAuth`, instead of stale query data.
`useAuth` correctly refreshes, and holds the up-to-date value of the currently logged-in user.
This is fixing the following issue:
1. User A is logged in, welcome screen is correct (Hi, A 👋🏼)
2. User A logs off
3. User B logs in, welcome screen is wrongly still showing A's welcome screen (Hi, A 👋🏼)
4. Refresh the page, and welcome screen is showing correctly (Hi, B 👋🏼)
=> 🐛 Fix welcome page to show logged-in user

frontend/biome.json, frontend/package.json, frontend/src/client/core/ApiError.ts, frontend/src/client/core/ApiRequestOptions.ts, frontend/src/client/core/ApiResult.ts, frontend/src/client/core/CancelablePromise.ts, frontend/src/client/core/OpenAPI.ts, frontend/src/client/core/request.ts, frontend/src/client/core/types.ts, frontend/src/client/index.ts, frontend/src/client/models.ts, frontend/src/client/schemas.ts, frontend/src/client/services.ts
Since Hey API's openapi-ts CLI `--format` flag doesn't work (and is completely removed in newer versions), "manually" run biomi to correctly format the auto-generated code.
Note that at times the default formatting is completely broken (see `schemas.ts` as an example), and at times it's inconsistent (see  `OpenAPI.ts` as an example).
=> 🎨 Run biome after OpenAPI client generation

frontend/src/routes/recover-password.tsx
=> ♻️ Refactor recover password

docker-compose.override.yml
This PR adds mailcather when running docker compose for development. This will allow developers to see the emails that are being sent from the application
=> ✨ Add mailcatcher configuration

frontend/src/components/Common/Navbar.tsx, frontend/src/routes/_layout/admin.tsx, frontend/src/routes/_layout/items.tsx
This PR aims to generalize the NavBar component allowing it to receive a Modal that handles the "Add" flow leaving the Modal control to the NavBar.
=> ♻️ Abstraction of specific AddModal component out of the Navbar

frontend/biome.json, frontend/src/components/Common/Navbar.tsx, frontend/src/routes/_layout/admin.tsx, frontend/src/routes/_layout/items.tsx, frontend/src/routes/login.tsx
=> 🎨 Format frontend

.env, frontend/src/hooks/useAuth.ts, frontend/src/routeTree.gen.ts, frontend/src/routes/login.tsx, frontend/src/routes/signup.tsx, release-notes.md
=> ✨ Add Sign Up and make `OPEN_USER_REGISTRATION=True` by default

frontend/package-lock.json, frontend/package.json, frontend/playwright.config.ts, frontend/tests/auth.setup.ts, frontend/tests/config.ts, frontend/tests/login.spec.ts, frontend/tsconfig.json
🔧 Update Playwright config and tests to use env variables
=> 🔧 Update Playwright config and tests to use env variables

frontend/src/routes/signup.tsx, frontend/tests/sign-up.spec.ts, frontend/tests/utils/random.ts
=> ✨ Add Sign Up e2e tests 

backend/app/alembic/env.py, backend/app/core/config.py
This PR changes alembic's `env` file to reuse database settings defined in `app.core.config` 😊
I've also taken the opportunity to allow having an empty `POSTGRES_PASSWORD`, when I develop locally I use https://postgresapp.com/ which creates a db without a password by default 😊
=> 🔧 Reuse database url from config in alembic setup

backend/app/core/config.py, backend/poetry.lock, backend/pyproject.toml
=> ⬆️ Update SQLModel to version `>=0.0.21`

frontend/tests/login.spec.ts, frontend/tests/reset-password.spec.ts, frontend/tests/sign-up.spec.ts, frontend/tests/user-settings.spec.ts, frontend/tests/utils/random.ts
♻️ Add random password util and refactor tests
=> ♻️ Add random password util and refactor tests

README.md, frontend/README.md
📝 Add End-to-End Testing with Playwright to frontend `README.md`
=> 📝 Add End-to-End Testing with Playwright to frontend `README.md`

frontend/Dockerfile
Fix warning in docker build...
```
=> [frontend internal] load build definition from Dockerfile                                                                                                                                          0.1s
=> => transferring dockerfile: 566B                                                                                                                                                                   0.0s
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 2)                                                                                                                         0.1s
```
=> 🚨 Fix Docker build warning

backend/app/models.py
ItemBase already contains the title field, so to me it seems defining the title field again in ItemCreate is redundant.
=> ♻️ Remove duplicate information in the ItemCreate model

backend/README.md
📝 Add Email Templates to `backend/README.md`
=> 📝 Add Email Templates to `backend/README.md`

.github/workflows/playwright.yml, .github/workflows/test.yml
Since `actions/upload-artifact` [v4.4.0](https://github.com/actions/upload-artifact/releases/tag/v4.4.0), hidden files are excluded by default. This PR specifically sets the `include-hidden-files` parameter to `True` to ensure all behaviour remains the same as before.
=> 💚 Set `include-hidden-files` to `True` when using the `upload-artifact` GH action

.github/workflows/playwright.yml, backend/app/api/routes/utils.py, docker-compose.yml, frontend/src/client/services.ts
This PR adds:
1. health check for the backend[1]
2. `--fail-on-flaky-tests` as a good practise to write less flaky tests, I assume in future you might want to disable this if your CI gets complex, but I think it should be turned on by default
3. `--trace=retain-on-failure` for easier debug when something fails (you can download the failing trace from the artifacts)
[1] Ideally you'd do some additional checks to see if we are able to connect to the backend, but for CI this is enough (we can also add health checks for the db if needed) 😊
=> 👷 Improve playwright CI job

docker-compose.yml
🔥 Enable support for Arm Docker images in Mac, remove old patch
=> 🔥 Enable support for Arm Docker images in Mac, remove old patch

docker-compose.yml
=> 🩺 Add DB healthcheck

.env, .github/workflows/playwright.yml, backend/README.md, backend/app/core/config.py, backend/app/utils.py, deployment.md, development.md, docker-compose.override.yml, docker-compose.yml, frontend/.env, frontend/README.md
♻️ Simplify domains with `api.example.com` for API and `dashboard.example.com` for frontend, improve local development with `localhost`
Simplify local development with the same ports as local reloading servers, this way it's easier to swap the Docker frontend for the local frontend and the Docker server for a local `fastapi dev` server or similar.
Having separated domains also opens the possibilities for deploying things even on different servers.
=> ♻️ Simplify domains with `api.example.com` for API and `dashboard.example.com` for frontend, improve local development with `localhost`

backend/app/core/config.py, backend/app/main.py
♻️ Include `FRONTEND_HOST` in CORS origins by default
=> ♻️ Include `FRONTEND_HOST` in CORS origins by default

backend/Dockerfile, docker-compose.override.yml, docker-compose.yml
♻️ Refactor prestart (migrations), move that to its own container
=> ♻️ Refactor prestart (migrations), move that to its own container

.github/workflows/test.yml, backend/Dockerfile, backend/README.md, backend/scripts/prestart.sh, backend/scripts/tests-start.sh, backend/tests-start.sh, docker-compose.yml, scripts/test-local.sh, scripts/test.sh
🚚 Move location of scripts to simplify file structure
=> 🚚 Move location of scripts to simplify file structure

backend/Dockerfile, backend/README.md, backend/scripts/prestart.sh, docker-compose.yml
🔧 Use plain base official Python Docker image
=> 🔧 Use plain base official Python Docker image

.github/dependabot.yml, .github/workflows/generate-client.yml, .github/workflows/latest-changes.yml, .github/workflows/lint-backend.yml, .github/workflows/smokeshow.yml, .github/workflows/test-backend.yml
👷 Update GitHub Actions format
=> 👷 Update GitHub Actions format

backend/app/utils.py
In the code, there is only this line: 
https://github.com/fastapi/full-stack-fastapi-template/blob/451c656fb052c9ff00e0da507a42d549c0f184cb/backend/app/utils.py#L1
```
response = message.send(to=email_to, smtp=smtp_options)
logging.info(f"send email result: {response}")
```
Without any log configuration (such as setting the log level, format, and handler), in most cases, this log message will not be displayed on the console, nor will it be automatically recorded in a log file.
https://github.com/fastapi/full-stack-fastapi-template/blob/451c656fb052c9ff00e0da507a42d549c0f184cb/backend/app/utils.py#L50C1-L51C51
I can't see the log `<emails.backend.SMTPResponse status_code=501 status_text=b'Mail from address must be same as authorization user.'>`
=> 🔊 Enable logging for email utils by default

frontend/src/components/Common/PaginationFooter.tsx, frontend/src/routes/_layout/admin.tsx, frontend/src/routes/_layout/items.tsx
Introduce common component `PaginationFooter` to handle pagination and reduce code duplication.
=> ♻️ Add PaginationFooter component

frontend/.gitignore
Currently when running playwright it creates a `.auth` folder which will contain a `user.json` file. This contains the `access_token` of the user used during testing. 
It's less then ideal and not needed to commit this to source, as such the path has been added to the `.gitignore` file.
=> 🔧 Add .auth playwright folder to `.gitignore`

development.md
Add MailCatcher URLs to docs and fix typo in URLs for API docs accessed through `localhost.tiangolo.com`.
=> 📝 Add MailCatcher to `development.md`

.github/workflows/playwright.yml, .github/workflows/test-docker-compose.yml, docker-compose.override.yml, frontend/.env, frontend/Dockerfile.playwright, frontend/playwright.config.ts, frontend/src/routes/_layout/admin.tsx, frontend/src/routes/_layout/items.tsx, frontend/tests/reset-password.spec.ts, frontend/tests/utils/mailcatcher.ts, frontend/tsconfig.json
👷 Improve Playwright CI speed: sharding (paralel runs), run in Docker to use cache, use env vars
=> 👷 Improve Playwright CI speed: sharding (paralel runs), run in Docker to use cache, use env vars

deployment.md
📝 Update `deployment.md`, instructions to install GitHub Runner in non-root VMs
=> 📝 Update `deployment.md`, instructions to install GitHub Runner in non-root VMs

frontend/README.md
Since openapi-ts was upgraded and  improved(https://github.com/fastapi/full-stack-fastapi-template/pull/1434, https://github.com/fastapi/full-stack-fastapi-template/pull/1430), we no longer need this step to simplify the names since the library will do this for us.
=> 📝 Removing deprecated manual client SDK step

frontend/src/components/Admin/AddUser.tsx, frontend/src/components/Admin/DeleteUser.tsx, frontend/src/components/Admin/EditUser.tsx, frontend/src/components/Common/ItemActionsMenu.tsx, frontend/src/components/Common/Navbar.tsx, frontend/src/components/Common/Sidebar.tsx, frontend/src/components/Common/SidebarItems.tsx, frontend/src/components/Common/UserActionsMenu.tsx, frontend/src/components/Common/UserMenu.tsx, frontend/src/components/Items/AddItem.tsx, frontend/src/components/Items/DeleteItem.tsx, frontend/src/components/Items/EditItem.tsx, frontend/src/components/UserSettings/Appearance.tsx, frontend/src/components/UserSettings/ChangePassword.tsx, frontend/src/components/UserSettings/DeleteConfirmation.tsx, frontend/src/components/UserSettings/UserInformation.tsx, frontend/src/hooks/useAuth.ts, frontend/src/hooks/useCustomToast.ts, frontend/src/routes/__root.tsx, frontend/src/routes/_layout.tsx, frontend/src/routes/_layout/admin.tsx, frontend/src/routes/_layout/index.tsx, frontend/src/routes/_layout/items.tsx, frontend/src/routes/_layout/settings.tsx, frontend/src/routes/login.tsx, frontend/src/routes/recover-password.tsx, frontend/src/routes/reset-password.tsx, frontend/src/routes/signup.tsx, frontend/tsconfig.json, frontend/vite.config.ts
🔧 Configure path alias for cleaner imports
=> 🔧 Configure path alias for cleaner imports

backend/app/core/config.py
Replaced email types from str to EmailStr in config.py because SQLModel supports it since version 0.0.19:
https://sqlmodel.tiangolo.com/release-notes/#0019
https://github.com/fastapi/sqlmodel/pull/966
=> ♻️ Replace email types from `str` to `EmailStr` in `config.py`

backend/app/tests/api/routes/test_login.py
🐛 Refactor reset password test to create normal user instead of using super user
=> 🐛 Refactor reset password test to create normal user instead of using super user

frontend/src/main.tsx, frontend/tests/login.spec.ts
♻️ Redirect the user to `login` if we get 401/403
=> ♻️ Redirect the user to `login` if we get 401/403

frontend/src/components/Common/Navbar.tsx, frontend/src/components/Common/Sidebar.tsx, frontend/src/components/UserSettings/ChangePassword.tsx, frontend/src/components/UserSettings/UserInformation.tsx, frontend/src/routes/_layout/index.tsx
=> 🎨 Add minor UI tweaks

frontend/src/components/Admin/EditUser.tsx
Issue when editting the user fields, It was required that you mandatory put the password and the new password. If for example you just want to edit the user "is_active" you are enforced to put a new password.
In my use case I set the "is_active" to false when someone signs up, and I want to enable one per one the users without changhing their password. 
I think that it is a bug because the empty password is already handled here:
```
const onSubmit: SubmitHandler<UserUpdateForm> = async (data) => {
if (data.password === "") {
data.password = undefined
}
mutation.mutate(data)
}
```
=> 🐛 Fix required password validation when editing user fields

frontend/src/components/Common/Sidebar.tsx
Issue (on mobile/small screens): The SidebarItems component has an onClose prop that's being passed to the RouterLink onClick handler, but in the Sidebar component, we are not passing this prop to SidebarItems. 
Fix: Now when a user clicks on any navigation item in the sidebar or the logout button, the drawer will automatically close as the new page loads. The onClose function is passed to each RouterLink in the SidebarItems component, which will trigger when a user clicks on a menu option.
=> 🐛 Close sidebar drawer on user selection

backend/app/models.py
title field is already defined in ItemBase
=> ♻️ Remove redundant field in inherited class

.github/dependabot.yml
🔧  Add npm and docker package ecosystems to Dependabot configuration
=> 🔧  Add npm and docker package ecosystems to Dependabot configuration

.github/workflows/generate-client.yml, backend/app/main.py, frontend/src/client/sdk.gen.ts, frontend/src/client/types.gen.ts
👷🏻‍♀️ Update CI for client generation 
Streamline development to run playwright tests locally.
=> 👷🏻‍♀️  Update CI for client generation

.pre-commit-config.yaml
This adds biome to the pre-commit hooks copied exactly as suggested in the docs: https://github.com/biomejs/pre-commit
=> 🔧 Add frontend linter pre-commit hook

backend/app/core/config.py
Fix the `parse_cors` function in `config.py` so that it behaves consistently for both empty string and empty list.
Currently, when an empty list is provided as an argument, it returns an empty list (`[]`). However, when an empty string (`""`) is provided, it returns a list with an empty string (`[""]`) and starting the FastAPI application fails.
=> 🐛 Fix `parse_cors` function to be consistent for both empty string and empty list
